CREATE TABLE ANIMAL
(
    ID          INTEGER      NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(250) NOT NULL,
    CLASS_TYPE  VARCHAR(250) NOT NULL,
    ORDER_TYPE  VARCHAR(250) NOT NULL,
    FAMILY      VARCHAR(250) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    REFERENCE   VARCHAR(250) NOT NULL,
    PRIMARY KEY (ID)
);